name: Build and Push to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front-next-ph2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./back-springboot-ph2
          push: true
          tags: ${{ secrets.DOCKERHUB_TOKEN }}/backend:latest

      - name: Connect homepage server and Execute Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
             git clone https://github.com/seokjunh/namoo-ph2.git
             git remote origin develop
             git checkout -b develop origin/develop

             cd /home/homepage/namoo-ph2-old/front-next-ph2
             cp .env.example .env.dev

             sudo nano .env.dev

             cc0db3300b2ed0a91cdb8590e5854ade
              
             docker compose down
             docker compose build --no-cache
             docker compose up -d
             
